version: "3.8"
services:
  frontend:
    build: frontend
    ports: 
      - 5000:5000
  backend:
    build: backend
    environment: 
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/game-elo-boost"
    ports: 
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017