version: "3.8"
services:
  frontend:
    build: frontend
    environment:
      baseURL: "http://localhost:3000"
    ports:
      - 5000:5000
  backend:
    build: backend
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb/game-elo-boost"
      FRONTEND_BASE_PATH: "http://localhost:5000"
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017